### ISSUE TITLE
Potentially useful data

### ISSUE THREAD

**Issue by audrism** [woc-hack/collab-graph#2]
1. The deforking approach reference https://github.com/ssc-oscar/forks
  p2P and P2p can be used to map back and forth. 

2. from a2P bigraph generated communities are in /da4_data/play/forks/P2AFullS.nA2A[uw].100.crank.map
This was done using OSLOM algorithm http://oslom.org/  (u for unweighted w for weighted)
A stands for aliased a (authors) see paper https://github.com/ssc-oscar/AuthorIDResolution
100 stands for filtering where Authors/Project with over 100 links are  excluded (bots/root/admin/large org)

3. zcat /da4_data/play/forks/P2AFullS.nA2Aw.100.crank.map | head -1
msni-terma <45007564+msni-terma@users.noreply.github.com>;Poul Hougaard <poh@terma.com>;0.001349

format is "author;central author'

**Comment by mahmoudjahanshahi** [comment]
@audrism 
Thank you. As I understood, the da4_data/play/forks/P2AFullS.nA2Aw.100.crank.map contains the generated communities and the mapping between each person with the central person in that community (25M authors connected to 4M communities) which can be definitely used by us somewhere down the road.

But for now, can you please advice where we can find the latest version of a2A mappings or auhtorIDResolution file which is mentioned in https://zenodo.org/record/3700859#.X7oqc2gzaM8 ? Or maybe we should somehow run our list against author metadata in mongodb to get the list of authors?

**Comment by audrism** [comment]
getValues a2A/A2a do the mapping. They may not include identity relationships to save space. 

Also, flat map in gz/a2AQ.s may be even more convenient

**Comment by mahmoudjahanshahi** [comment]
Actually a2A/A2a does not seem to work and gives the following error:

    ls: cannot access /da?_data/basemaps/a2AFullR.31.tch: No such file or directory
    Pseudo-terminal will not be allocated because stdin is not a terminal.
    ssh: Could not resolve hostname ~/lookup/getvalues.perl --flat=n : Name or service not known

I will try the flat map as you suggested, thank you

**Comment by audrism** [comment]
you might try git pull on you lookup repo
